# Generated by Django 5.2.7 on 2025-12-09 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Math', 'Math'), ('Science', 'Science')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('problem_text', models.TextField()),
                ('solution', models.TextField(help_text='Detailed solution/guide shown to students')),
                ('correct_answer', models.TextField(blank=True, default='', help_text='Exact answer used for auto-grading')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Teacher who authored the problem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('was_correct', models.BooleanField(default=False)),
                ('answer_given', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to='problems.problem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('student_answer', models.TextField(blank=True, null=True)),
                ('first_attempted_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempted_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='problems.problem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problem Progress',
                'verbose_name_plural': 'Problem Progress',
                'ordering': ['-last_attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['subject', 'difficulty'], name='problems_pr_subject_c49a58_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['topic'], name='problems_pr_topic_97bebe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together={('title', 'subject', 'topic')},
        ),
        migrations.AlterUniqueTogether(
            name='problemprogress',
            unique_together={('student', 'problem')},
        ),
    ]
